config/routes.rb
Rails.application.routes.draw do
  devise_for :users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'home#index'

  get 'home/index'

  resources :listening_lessons do
    resources :submitted_scripts
  end
end

app/models/antonym.rb
class Antonym < ApplicationRecord
  serialize :content, Array

  belongs_to :word
  belongs_to :meaning
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dictionary.rb
class Dictionary < ApplicationRecord
  validates :name, uniqueness: true
end

app/models/example.rb
class Example < ApplicationRecord
  belongs_to :meaning
end

app/models/listening_lesson.rb
class ListeningLesson < ApplicationRecord
  has_many :submitted_scripts

  validates :name, :link, presence: true

  def script_submitted_by?(user)
    script = self.submitted_scripts.find_by(user: user)
    !!script
  end
end

app/models/meaning.rb
class Meaning < ApplicationRecord
  belongs_to :word
  belongs_to :dictionary

  has_many :examples, dependent: :destroy
  has_many :synonyms, dependent: :destroy
  has_many :antonyms, dependent: :destroy
end

app/models/pronunciation.rb
class Pronunciation < ApplicationRecord
  serialize :dialects, Array

  belongs_to :word
end

app/models/submitted_script.rb
class SubmittedScript < ApplicationRecord
  belongs_to :user
  belongs_to :listening_lesson
end

app/models/synonym.rb
class Synonym < ApplicationRecord
  serialize :content, Array

  belongs_to :word
  belongs_to :meaning
end

app/models/translation_history.rb
class TranslationHistory < ApplicationRecord
 belongs_to :user
 belongs_to :word
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :submitted_scripts
end

app/models/word.rb
class Word < ApplicationRecord
  has_one :pronunciation, dependent: :destroy
  has_many :meanings, dependent: :destroy
  has_many :examples, through: :meanings
  has_many :synonyms
  has_many :antonyms
  has_many :translation_histories, dependent: :destroy

  validates :name, presence: true

  before_create :update_vietnamese_meanings
  before_create :update_google_images

  private

  def update_vietnamese_meanings
    self.vn_meanings = MeaningService.update_mean_from_internet(name)
  end

  def update_google_images
    self.images = GoogleImageService.get_img_src(name)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery prepend: true
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if params['q']
      query_word = params['q'].strip.downcase
      word = Word.find_or_create_by(name: query_word, language: 'en')
      word_updated = word && word.updated
      unless word_updated
        OxfordDictionariesService.new.search(query_word)
        WordsApiService.new.search(query_word)
      end
      word.update updated: true
    end

    @word = word || Word.find_by(name: query_word)
    if @word
      @pronunciation = @word.pronunciation
      @meanings = @word.meanings.includes(:examples, :synonyms, :antonyms)
      if current_user
        history = TranslationHistory.find_by user: current_user, word: @word
        if history
          history.update_columns translated_count: history.translated_count + 1
        else
          TranslationHistory.create user: current_user, word: @word
        end
      end
    end
    if current_user
      @typical_words = Word.joins(:translation_histories).limit(15).order("translation_histories.translated_count desc").uniq
    end
  end
end

app/controllers/listening_lessons_controller.rb
class ListeningLessonsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_listening_lesson, only: [:show, :edit, :update, :destroy]

  # GET /listening_lessons
  # GET /listening_lessons.json
  def index
    @listening_lessons = ListeningLesson.all.order(:name)
  end

  # GET /listening_lessons/1
  # GET /listening_lessons/1.json
  def show
  end

  # GET /listening_lessons/new
  def new
    @listening_lesson = ListeningLesson.new
  end

  # GET /listening_lessons/1/edit
  def edit
  end

  # POST /listening_lessons
  # POST /listening_lessons.json
  def create
    @listening_lesson = ListeningLesson.new(listening_lesson_params)

    respond_to do |format|
      if @listening_lesson.save
        format.html { redirect_to @listening_lesson, notice: 'Listening lesson was successfully created.' }
        format.json { render :show, status: :created, location: @listening_lesson }
      else
        format.html { render :new }
        format.json { render json: @listening_lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /listening_lessons/1
  # PATCH/PUT /listening_lessons/1.json
  def update
    respond_to do |format|
      if @listening_lesson.update(listening_lesson_params)
        format.html { redirect_to @listening_lesson, notice: 'Listening lesson was successfully updated.' }
        format.json { render :show, status: :ok, location: @listening_lesson }
      else
        format.html { render :edit }
        format.json { render json: @listening_lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listening_lessons/1
  # DELETE /listening_lessons/1.json
  def destroy
    @listening_lesson.destroy
    respond_to do |format|
      format.html { redirect_to listening_lessons_url, notice: 'Listening lesson was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listening_lesson
      @listening_lesson = ListeningLesson.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def listening_lesson_params
      params.require(:listening_lesson).permit(:name, :link, :script)
    end
end

app/controllers/searched_words_controller.rb
class SearchedWordsController < ApplicationController
  def create
    SearchedWord.create word: params[:word]
  end
end

app/controllers/submitted_scripts_controller.rb
class SubmittedScriptsController < ApplicationController
  before_action :authenticate_user!

  def new
    @submitted_script = SubmittedScript.new user: current_user, listening_lesson_id: params[:listening_lesson_id]
  end

  def create
    script = SubmittedScript.new submitted_script_params

    if script.save
      redirect_to listening_lesson_path(script.listening_lesson)
    end
  end

  def edit
    @submitted_script = SubmittedScript.find params[:id]
  end

  def update
    script = SubmittedScript.find params[:id]
    script.update submitted_script_params

    if script.save
      redirect_to listening_lesson_path(script.listening_lesson)
    end
  end

  private
  def submitted_script_params
    params.require(:submitted_script).permit(:user_id, :listening_lesson_id, :content)
  end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for user, option = {size: Settings.avatar.size}
    gravatar_id = Digest::MD5::hexdigest user.email.downcase
    size = option[:size]
    gravatar_url = "http://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag gravatar_url, alt: user.username, class: "gravatar"
  end
end

app/helpers/form_tag_helper.rb
module FormTagHelper
  # see http://api.rubyonrails.org/classes/ActionView/Helpers/FormTagHelper.html#method-i-utf8_enforcer_tag
  def utf8_enforcer_tag
    ''.html_safe
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/listening_lessons_helper.rb
module ListeningLessonsHelper
end

app/views/home/index.html.haml
- meta title: 'Your own dictionary',
  description: 'Create your own dictionary',
  keywords: %w(dictionary with-synonym with-antonym)
%div.row
  %div.col.align-self-center
    %h1 Dictionary

    = form_tag(home_index_path, method: :get, class: 'form-inline search-form') do
      %div.row.justify-content-start.search-word
        %input.form-control.col-8{"type" => "text", "placeholder" => "Search for...", "aria-label" => "Search for...", "name" => "q"}
        %button.btn.btn-outline-success.search-button.col-2{"type" => "submit"} Go!
    - if @word
      %h2= @word.name
      %span= @pronunciation.try(:phonetic_spelling)
      %ul
        %li= @word.vn_meanings.first(4).join(", ")
        %img.img-fluid{"src" => @word.images[0], "width" => "400"}
        %img.img-fluid{"src" => @word.images[1], "width" => "400"}
        - if @meanings.present?
          - @meanings.each do |meaning|
            %li= meaning.definition.capitalize
            %div.examples= meaning.examples.pluck(:content).map(&:capitalize).join(' | ')
            - synonyms = meaning.synonyms.pluck(:content).flatten.join(', ')
            - if synonyms.present?
              .synonyms
                Synonyms:
                = synonyms
            - antonyms = meaning.antonyms.pluck(:content).flatten.join(', ')
            - if antonyms.present?
              .antonyms
                Antonyms:
                = antonyms

    %br
    %h2 Typical words
    - if @typical_words
      %ul
        - @typical_words.each do |word|
          %li
            %span= link_to word.name, home_index_path(q: word.name)
            %span= "/#{word.pronunciation.try(:phonetic_spelling)}/"

app/views/submitted_scripts/_form.html.haml
= form_for [@submitted_script.listening_lesson ,@submitted_script] do |f|
  - if @submitted_script.errors.any?
    #error_explanation
      %h2= "#{pluralize(@submitted_script.errors.count, "error")} prohibited this submitted_script from being saved:"
      %ul
        - @submitted_script.errors.full_messages.each do |message|
          %li= message

  = f.hidden_field :user_id
  = f.hidden_field :listening_lesson_id
  .field
    %audio.listening-audio{ controls: '' }
      %source{ src: @submitted_script.listening_lesson.link, type: 'audio/mpeg' }
      Your browser does not support the audio element.
  .field.form-group
    = f.label :content
    = f.text_area :content, class: 'form-control script-content'
  .actions
    = f.submit 'Save', class: 'btn btn-success'

app/views/submitted_scripts/edit.html.haml
%h4 Listen carefully and submit your script.
= render 'form'

app/views/submitted_scripts/new.html.haml
%h2 Add new script
= render 'form'