config/routes.rb
Rails.application.routes.draw do
  devise_for :users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'home#index'

  get 'home/index'

  resources :listening_lessons do
    resources :submitted_scripts
  end
end

app/models/listening_lesson.rb
class ListeningLesson < ApplicationRecord
  has_many :submitted_scripts

  validates :name, :link, presence: true

  def script_submitted_by?(user)
    script = self.submitted_scripts.find_by(user: user)
    !!script
  end
end

app/controllers/listening_lessons_controller.rb
class ListeningLessonsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_listening_lesson, only: [:show, :edit, :update, :destroy]

  # GET /listening_lessons
  # GET /listening_lessons.json
  def index
    @listening_lessons = ListeningLesson.all.order(:name)
  end

  # GET /listening_lessons/1
  # GET /listening_lessons/1.json
  def show
  end

  # GET /listening_lessons/new
  def new
    @listening_lesson = ListeningLesson.new
  end

  # GET /listening_lessons/1/edit
  def edit
  end

  # POST /listening_lessons
  # POST /listening_lessons.json
  def create
    @listening_lesson = ListeningLesson.new(listening_lesson_params)

    respond_to do |format|
      if @listening_lesson.save
        format.html { redirect_to @listening_lesson, notice: 'Listening lesson was successfully created.' }
        format.json { render :show, status: :created, location: @listening_lesson }
      else
        format.html { render :new }
        format.json { render json: @listening_lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /listening_lessons/1
  # PATCH/PUT /listening_lessons/1.json
  def update
    respond_to do |format|
      if @listening_lesson.update(listening_lesson_params)
        format.html { redirect_to @listening_lesson, notice: 'Listening lesson was successfully updated.' }
        format.json { render :show, status: :ok, location: @listening_lesson }
      else
        format.html { render :edit }
        format.json { render json: @listening_lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listening_lessons/1
  # DELETE /listening_lessons/1.json
  def destroy
    @listening_lesson.destroy
    respond_to do |format|
      format.html { redirect_to listening_lessons_url, notice: 'Listening lesson was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listening_lesson
      @listening_lesson = ListeningLesson.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def listening_lesson_params
      params.require(:listening_lesson).permit(:name, :link, :script)
    end
end

app/helpers/listening_lessons_helper.rb
module ListeningLessonsHelper
end

app/views/listening_lessons/_form.html.haml
= form_for @listening_lesson do |f|
  - if @listening_lesson.errors.any?
    #error_explanation
      %h2= "#{pluralize(@listening_lesson.errors.count, "error")} prohibited this listening_lesson from being saved:"
      %ul
        - @listening_lesson.errors.full_messages.each do |message|
          %li= message

  .field.form-group
    = f.label :name
    = f.text_field :name, class: 'form-control'
  .field.form-group
    = f.label :link
    = f.text_field :link, class: 'form-control'
  .field.form-group
    = f.label :script
    = f.text_area :script, class: 'form-control script-content'
  .actions
    = f.submit 'Save', class: 'btn btn-success'

app/views/listening_lessons/edit.html.haml
%h1 Editing listening_lesson

= render 'form'

= link_to 'Show', @listening_lesson
\|
= link_to 'Back', listening_lessons_path

app/views/listening_lessons/index.html.haml
- meta title: 'Listening Lessons',
  description: 'Listening and write script',
  keywords: %w(listening listen-and-write ielts 1-minute-listening)
- breadcrumb :listening_lessons
%h1 Listening Lessons
- length = @listening_lessons.length
- each_length = length / 2
%div= link_to 'New Listening Lesson', new_listening_lesson_path
.lesson-index
  - for i in 0..1 do
    %table.listening-table.col-md-6
      %thead
        %tr
          %th Name
          %th
          %th
          %th
      %tbody
        - @listening_lessons[i*each_length..(i+1)*each_length].each do |listening_lesson|
          %tr
            %td= listening_lesson.name
            %td= link_to 'Show', listening_lesson
            %td= link_to 'Edit', edit_listening_lesson_path(listening_lesson)
            %td
              - script = listening_lesson.submitted_scripts.find_by(user: current_user)
              - if script
                = link_to 'Re-listen', edit_listening_lesson_submitted_script_path(listening_lesson, script)
              - else
                = link_to 'Listen', new_listening_lesson_submitted_script_path(listening_lesson)

app/views/listening_lessons/new.html.haml
%h1 New listening_lesson

= render 'form'

= link_to 'Back', listening_lessons_path

app/views/listening_lessons/show.html.haml
- breadcrumb :lesson, @listening_lesson
%p#notice= notice

#display

%p
  %b Name:
  = @listening_lesson.name
%p
  = @listening_lesson.link
%p
  %audio.listening-audio{ controls: '' }
    %source{ src: @listening_lesson.link, type: 'audio/mpeg' }
    Your browser does not support the audio element.
%p
  %b Script:
  .answer-script= @listening_lesson.script

%h3 Submitted scripts from users
- @listening_lesson.submitted_scripts.each do |script|
  .user-script
    %span.italic-text
      Submitted by
      = script.user.fullname.presence || script.user.username.presence || script.user.email
    .script
      %p.script-content= script.content

= link_to 'Edit', edit_listening_lesson_path(@listening_lesson)
\|
= link_to 'Back', listening_lessons_path

:javascript
  $(document).ready(function() {
    var color = '', span = null;

    const answerScript = $(".answer-script")[0].textContent;
    $(".user-script .script").each(function(index, script) {
      const userScript = $(script).find(".script-content").text();
      var diff = Diff.diffWordsWithSpace(userScript, answerScript, { ignoreCase: true }),
      display = document.getElementById('display'),
      fragment = document.createDocumentFragment();

      diff.forEach(function(part){
        className = part.added ? 'text-added' : part.removed ? 'text-removed' : '';
        span = document.createElement('span');
        span.className = className;
        span.appendChild(document.createTextNode(part.value));
        fragment.appendChild(span);
      });

      script.appendChild(fragment);
    });
  });